// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://chdbqxtasxiibgncrhdf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNoZGJxeHRhc3hpaWJnbmNyaGRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5Mzk3NDgsImV4cCI6MjA2OTUxNTc0OH0.1B7COnSrVReI6J20GjaLdxh9ymWNB0W68tQBOlOKano";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});